# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='money',
            field=models.CharField(default=1, max_length=32),
        ),
    ]
